-- =============================================================
-- Seed: 001_terms
-- Feature:   SPEC-003 - Gameplay "Pokémon o Venezolano"
-- Created:   2026-04-15
-- Author:    database-agent
-- Notes:     Idempotente — usa INSERT ... ON CONFLICT DO NOTHING.
--            Requiere que la tabla `terms` exista (002_create_terms_table.sql).
-- =============================================================

-- ============================================================
-- UP  (insertar datos semilla)
-- ============================================================

INSERT INTO terms (text, category) VALUES
  -- ── Pokémon (50 términos de diferentes generaciones) ──────────────────────
  ('Charmander',   'pokemon'),
  ('Pikachu',      'pokemon'),
  ('Bulbasaur',    'pokemon'),
  ('Squirtle',     'pokemon'),
  ('Jigglypuff',   'pokemon'),
  ('Eevee',        'pokemon'),
  ('Mewtwo',       'pokemon'),
  ('Gengar',       'pokemon'),
  ('Onix',         'pokemon'),
  ('Snorlax',      'pokemon'),
  ('Geodude',      'pokemon'),
  ('Machop',       'pokemon'),
  ('Diglett',      'pokemon'),
  ('Psyduck',      'pokemon'),
  ('Caterpie',     'pokemon'),
  ('Weedle',       'pokemon'),
  ('Rattata',      'pokemon'),
  ('Pidgey',       'pokemon'),
  ('Zubat',        'pokemon'),
  ('Abra',         'pokemon'),
  ('Kadabra',      'pokemon'),
  ('Dragonite',    'pokemon'),
  ('Lapras',       'pokemon'),
  ('Togepi',       'pokemon'),
  ('Marill',       'pokemon'),
  ('Wobbuffet',    'pokemon'),
  ('Mudkip',       'pokemon'),
  ('Torchic',      'pokemon'),
  ('Gardevoir',    'pokemon'),
  ('Flygon',       'pokemon'),
  ('Lucario',      'pokemon'),
  ('Garchomp',     'pokemon'),
  ('Toxicroak',    'pokemon'),
  ('Mimikyu',      'pokemon'),
  ('Rowlet',       'pokemon'),
  ('Litten',       'pokemon'),
  ('Popplio',      'pokemon'),
  ('Wooloo',       'pokemon'),
  ('Corviknight',  'pokemon'),
  ('Ditto',        'pokemon'),
  ('Magikarp',     'pokemon'),
  ('Gyarados',     'pokemon'),
  ('Alakazam',     'pokemon'),
  ('Haunter',      'pokemon'),
  ('Clefairy',     'pokemon'),
  ('Vulpix',       'pokemon'),
  ('Growlithe',    'pokemon'),
  ('Poliwag',      'pokemon'),
  ('Oddish',       'pokemon'),
  ('Bellsprout',   'pokemon'),
  ('Jolteon',      'pokemon'),
  ('Lugia',        'pokemon'),
  ('Arcanine',     'pokemon'),
  ('Primarina',    'pokemon'),
  ('Rapidash',     'pokemon'),
  ('Darmanitan',   'pokemon'),
  ('Jynx',         'pokemon'),
  ('Kommo-o',      'pokemon'),
  ('Aegislash',    'pokemon'),
  ('Ludicolo',     'pokemon'),
  ('Milotic',      'pokemon'),
  ('Yveltal',      'pokemon'),
  ('Carnivine',    'pokemon'),
  ('Jumpluff',     'pokemon'),
  ('Yanmega',      'pokemon'),
  ('Infernape',    'pokemon'),
  ('Pidgeot',      'pokemon'),
  ('Yamper',       'pokemon'),
  ('Sylveon',      'pokemon'),
  ('Cresselia',    'pokemon'),
  ('Meloetta',     'pokemon'),

  -- ── Venezolano (50 + 35 nombres venezolanos) ─────────────────────────────
  ('Arepa',        'venezolano'),
  ('Cachapa',      'venezolano'),
  ('Hallaca',      'venezolano'),
  ('Tequeño',      'venezolano'),
  ('Pabellón',     'venezolano'),
  ('Guarapo',      'venezolano'),
  ('Papelón',      'venezolano'),
  ('Chimó',        'venezolano'),
  ('Chamo',        'venezolano'),
  ('Catire',       'venezolano'),
  ('Sifrino',      'venezolano'),
  ('Pana',         'venezolano'),
  ('Marico',       'venezolano'),
  ('Burda',        'venezolano'),
  ('Ladilla',      'venezolano'),
  ('Gafo',         'venezolano'),
  ('Cambur',       'venezolano'),
  ('Lechosa',      'venezolano'),
  ('Guayoyo',      'venezolano'),
  ('Morocho',      'venezolano'),
  ('Patacón',      'venezolano'),
  ('Mandoca',      'venezolano'),
  ('Golfeado',     'venezolano'),
  ('Cachito',      'venezolano'),
  ('Fosforera',    'venezolano'),
  ('Perolita',     'venezolano'),
  ('Chuzo',        'venezolano'),
  ('Güevón',       'venezolano'),
  ('Coroto',       'venezolano'),
  ('Corotico',     'venezolano'),
  ('Chévere',      'venezolano'),
  ('Chola',        'venezolano'),
  ('Tusera',       'venezolano'),
  ('Macundales',   'venezolano'),
  ('Mecate',       'venezolano'),
  ('Cocuy',        'venezolano'),
  ('Pasticho',     'venezolano'),
  ('Birra',        'venezolano'),
  ('Gandola',      'venezolano'),
  ('Cotufa',       'venezolano'),
  ('Pavita',       'venezolano'),
  ('Zamuro',       'venezolano'),
  ('Cuaima',       'venezolano'),
  ('Sapoara',      'venezolano'),
  ('Bochinche',    'venezolano'),
  ('Perico',       'venezolano'),
  ('Bachaco',      'venezolano'),
  ('Taguara',      'venezolano'),
  ('Palmarejo',    'venezolano'),
  ('Guacharo',     'venezolano'),
  ('Yorman',       'venezolano'),
  ('Yosmar',       'venezolano'),
  ('Maikel',       'venezolano'),
  ('Yuleisy',      'venezolano'),
  ('Yorgelis',     'venezolano'),
  ('Ender',        'venezolano'),
  ('Yuleima',      'venezolano'),
  ('Wilmer',       'venezolano'),
  ('Yennifer',     'venezolano'),
  ('Yusleidy',     'venezolano'),
  ('Jhosmar',      'venezolano'),
  ('Carleisy',     'venezolano'),
  ('Luismar',      'venezolano'),
  ('Andrelis',     'venezolano'),
  ('Pedrimar',     'venezolano'),
  ('Migleisy',     'venezolano'),
  ('Rafelis',      'venezolano'),
  ('Danimar',      'venezolano'),
  ('Josleiny',     'venezolano'),
  ('Carlimar',     'venezolano'),
  ('Andryelis',    'venezolano'),
  ('Jhonleisy',    'venezolano'),
  ('Luisdrel',     'venezolano'),
  ('Marleisy',     'venezolano'),
  ('Yandriela',    'venezolano'),
  ('Carleiny',     'venezolano'),
  ('Josmary',      'venezolano'),
  ('Yormanis',     'venezolano'),
  ('Andresmar',    'venezolano'),
  ('Pedrelys',     'venezolano'),
  ('Yorandri',     'venezolano'),
  ('Luisyelis',    'venezolano'),
  ('Jhoseidy',     'venezolano'),
  ('Carleysi',     'venezolano'),
  ('Yormanely',    'venezolano')

ON CONFLICT (text) DO NOTHING;


-- ============================================================
-- DOWN  (eliminar solo los datos insertados por este seed)
-- ============================================================

-- DELETE FROM terms WHERE text IN (
--   'Charmander','Pikachu','Bulbasaur','Squirtle','Jigglypuff','Eevee','Mewtwo',
--   'Gengar','Onix','Snorlax','Geodude','Machop','Diglett','Psyduck','Caterpie',
--   'Weedle','Rattata','Pidgey','Zubat','Abra','Kadabra','Dragonite','Lapras',
--   'Togepi','Marill','Wobbuffet','Mudkip','Torchic','Gardevoir','Flygon',
--   'Lucario','Garchomp','Toxicroak','Mimikyu','Rowlet','Litten','Popplio',
--   'Wooloo','Corviknight','Ditto','Magikarp','Gyarados','Alakazam','Haunter',
--   'Clefairy','Vulpix','Growlithe','Poliwag','Oddish','Bellsprout',
--   'Arepa','Cachapa','Hallaca','Tequeño','Pabellón','Guarapo','Papelón',
--   'Chimó','Chamo','Catire','Sifrino','Pana','Marico','Burda','Ladilla',
--   'Gafo','Cambur','Lechosa','Guayoyo','Morocho','Patacón','Mandoca',
--   'Golfeado','Cachito','Fosforera','Perolita','Chuzo','Güevón','Coroto',
--   'Corotico','Chévere','Chola','Tusera','Macundales','Mecate','Cocuy',
--   'Pasticho','Birra','Gandola','Cotufa','Pavita','Zamuro','Cuaima',
--   'Sapoara','Bochinche','Perico','Bachaco','Taguara','Palmarejo','Guacharo'
-- );
